apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  name: srikanth
  company: CC
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
  labels:
    app: cm
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ["sh", "-c", "echo My name $name working at $company && sleep 3600"]
    envFrom:
    - configMapRef:
        name: my-cm